# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: haram
google_analytics: dbyll
title: haram

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      imamge: true
      title: Haram's Note

description: Stylish Jekyll Theme
author:
  profile_image: /assets/mh.jpg
  profile_size: 150
  name: Haram
  email: jmh667722@gmail.com
  github: jmh6672
  instagram: https://www.instagram.com/jeongmyunghan
  bio: 힝구앵구잉잉
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
#sidebar_background_image: /assets/mh.jpg
sidebar_background_color: black

BASE_PATH:

plugins:
  - jekyll-paginate
